# Generated by Django 2.1.15 on 2020-02-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200210_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
