# Generated by Django 2.1.15 on 2020-02-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recipe_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minutes',
            new_name='totalTime',
        ),
    ]
