# Generated by Django 2.1.15 on 2020-02-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200211_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeIngredient',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeInstruction',
            field=models.TextField(blank=True),
        ),
    ]
