# Generated by Django 2.1.15 on 2020-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200212_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeYield',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
