# Generated by Django 2.1.15 on 2020-02-12 18:35

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200212_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to=core.models.recipe_image_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='aggregateRatings',
            field=models.ManyToManyField(blank=True, to='core.AggregateRating'),
        ),
    ]
