# Generated by Django 2.1.15 on 2020-02-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200212_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='aggregateRatings',
            new_name='aggregateRating',
        ),
    ]
